# the minimum disks required for distributed minio is 4,
# same as minimum disks required for erasure coding.

# a distributed minio setup with m servers and n disks will have your data safe,
# as long as m/2 servers or m*n/2 or more disks are online.

# minio follows strict read-after-write and list-after-write consistency model
# for all I/O operations both in distributed and standalone modes.

# servers running distributed minio instances should be less than 15 minutes apart.
# you can enable NTP service as a best practice to ensure same times across servers.

version: "3.7"
services:
  minio1:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    ports:
      - "19000:9000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=admin12345
    command: server http://minio{1...4}/data{1...4}
    volumes:
      - ~/minio/mapreduce/data1-1:/data1
      - ~/minio/mapreduce/data1-2:/data2
      - ~/minio/mapreduce/data1-3:/data3
      - ~/minio/mapreduce/data1-4:/data4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    ports:
      - "19001:9000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=admin12345
    command: server http://minio{1...4}/data{1...4}
    volumes:
      - ~/minio/mapreduce/data2-1:/data1
      - ~/minio/mapreduce/data2-2:/data2
      - ~/minio/mapreduce/data2-3:/data3
      - ~/minio/mapreduce/data2-4:/data4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    ports:
      - "19002:9000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=admin12345
    command: server http://minio{1...4}/data{1...4}
    volumes:
      - ~/minio/mapreduce/data3-1:/data1
      - ~/minio/mapreduce/data3-2:/data2
      - ~/minio/mapreduce/data3-3:/data3
      - ~/minio/mapreduce/data3-4:/data4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    ports:
      - "19003:9000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=admin12345
    command: server http://minio{1...4}/data{1...4}
    volumes:
      - ~/minio/mapreduce/data4-1:/data1
      - ~/minio/mapreduce/data4-2:/data2
      - ~/minio/mapreduce/data4-3:/data3
      - ~/minio/mapreduce/data4-4:/data4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3